### ISSUE TITLE
Access denied for user 'root'@'localhost'，然而没用root账号

### ISSUE THREAD

**Issue by tomriddle1234** [itning/Student-Homework-Management-System#8]
先看

```
2019-08-24 13:35:58.654 [Druid-ConnectionPool-Create-1855287620] ERROR c.alibaba.druid.pool.DruidDataSource - create connection SQLException, url: jdbc:mysql://localhost:3306/shw?user=myuser&password=mypass&createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf-8&useSSL=false&autoReconnect=true&failOverReadOnly=false&connectTimeout=0&serverTimezone=UTC, errorCode 0, state 08001
java.sql.SQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:526)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:513)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:505)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:479)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:489)
	at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:1677)
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:1601)
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:633)
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:347)
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:219)
	at com.alibaba.druid.filter.FilterChainImpl.connection_connect(FilterChainImpl.java:156)
	at com.alibaba.druid.filter.stat.StatFilter.connection_connect(StatFilter.java:218)
	at com.alibaba.druid.filter.FilterChainImpl.connection_connect(FilterChainImpl.java:150)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1598)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1662)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:2697)
Caused by: com.mysql.cj.core.exceptions.CJException: Access denied for user 'root'@'localhost' (using password: YES)
	at sun.reflect.GeneratedConstructorAccessor78.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.cj.core.exceptions.ExceptionFactory.createException(ExceptionFactory.java:54)
	at com.mysql.cj.core.exceptions.ExceptionFactory.createException(ExceptionFactory.java:93)
	at com.mysql.cj.core.exceptions.ExceptionFactory.createException(ExceptionFactory.java:133)
	at com.mysql.cj.core.exceptions.ExceptionFactory.createException(ExceptionFactory.java:117)

```

然而`context.properties`里面已经

```
driverClass=com.mysql.cj.jdbc.Driver
jdbcUrl=jdbc:mysql://localhost:3306/shw?user=myuser&password=mypass&createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf-8&useSSL=false&autoReconnect=true&failOverReadOnly=false&connectTimeout=0&serverTimezone=UTC
user=myuser
password=mypass
globalSessionTimeout=1800000
maxAge=2592000
maxUploadSize=209715200
upLoadFilePath=/data/hwupload/
```

**Comment by itning** [comment]
```mvn clean```
```mvn package```
试试
可能有缓存

**Comment by tomriddle1234** [comment]
刚刚试过还是不行。

请问相关的登陆代码哪个文件？

**Comment by itning** [comment]
> 刚刚试过还是不行。
> 
> 请问相关的登陆代码哪个文件？

[https://github.com/itning/Student-Homework-Management-System/blob/master/src/main/resources/applicationContext.xml#L22](https://github.com/itning/Student-Homework-Management-System/blob/master/src/main/resources/applicationContext.xml#L22)

**Comment by tomriddle1234** [comment]
感谢，我还在处理这个问题。
我的MySQL版本是5.6.45，虽然是5.6但是是比较新的版本，是不是mysql-connector-java这个库需要版本新一点的？
我正在彻底删除本地maven的cache再install一遍

**Comment by tomriddle1234** [comment]
你好，我在本地调试解决了这个问题，`context.properties`和`applicationContext.xml`里面`user`和`password`分别改了名字，比如`dbuser`,`dbpassword`就解决了。

我同时升级了mysql-connector-java 到8.0.17好像也没问题。
